### ISSUE TITLE
Emit more events

### ISSUE THREAD

**Issue by ThomWright** [mpirik/postgres-pool#1]
Hi,

I really like the look of this pool library, and I'm considering replacing `pg-pool` with it.

One thing I'd like is to be notified of some events so I can keep track of activity in the pool for monitoring purposes.

Would you accept a PR to emit events for the following?

- request entering connection queue
- request being removed from the connection queue
- connection being added to the pool
- connection being removed from the pool
- connection entering idle state
- connection leaving idle state

I'm struggling to think of good names for them. Any ideas?

**Comment by jgeurts** [comment]
Yeah, I'd be interested in a PR. Naming things is hard... maybe something like:

* requestQueue
* requestDequeue
* connectionAdded
* connectionRemoved
* connectionIdle
* connectionActive

**Comment by ThomWright** [comment]
`connectionActive` doesn't quite describe the event of a connection leaving the idle state, since it could be being removed after a timeout.

How about:

- requestQueued
- requestDequeued
- connectionAdded
- connectionRemoved
- connectionIdled
- connectionUndled

`connectionUnidled` is a bit awkward, but the tense matches nicely.

I'll see if I can find time to do this soon.

**Comment by jgeurts** [comment]
Hi @ThomWright, I released v1.0.5 with those events added. Please let me know if you had something else in mind! Thanks for the suggestion!

**Comment by ThomWright** [comment]
Thanks, that's great!

Instead of the `idleConnectionActivated` event, I was looking for an event to be triggered whenever a connection is removed from the idle list, including [here](https://github.com/mpirik/postgres-pool/blob/a9527f7429e6726113795497d2c456287371d242/src/index.ts#L260).

That said, this is really useful, the most useful thing for me is to keep a count of how many connection requests get queued rather than being serviced immediately, which I can now do :ok_hand:

**Comment by jgeurts** [comment]
👍 Glad it's working for you! fwiw, in v1.0.6, I added `connectionRemovedFromIdlePool` based on your comment.
